stages:
  - test
  - build
  - deploy

#  .validate: &validate // This is how you can define a job and reuse itSS
#   script:
#     - npm install
#     - npm run lint
#     - npm run type-check
#     - npm run test

# Build job 
build_frontend:
  stage: build
  # extends: .validate // This is how you can use the validate job
  image: node:16  # alpine is a lightweight image
  script:
    - cd Frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      -  Frontend/.next
      # next js libary installed in deply job 

build_backend:
  stage: build
  image: node:16
  script:
    - cd Backend
    - npm install

  artifacts:
    paths:
      - Backend/


# Test Stage node jov


.test: # hiden job
  stage: test
  image: node:16
  script:
    - npm install
    - npm test

# Deploy to Vercel
deploy-vercel:
  stage: deploy
  image: node:16
  script:
    # - cd Frontend
    - npm install -g vercel
    - vercel --token $VERCEL_TOKEN --prod
  only:
    - main  # Deploy only on the main branch
