stages:
  - build
  - deploy

# Build job 
build_frontend:
  stage: build
  # extends: .validate // This is how you can use the validate job
  image: node:16  # alpine is a lightweight image
  script:
    - cd Frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      -  Frontend/.next
      # next js libary installed in deply job 



# Test Stage node jov


.test: # hiden job
  stage: test
  image: node:16
  script:
    - npm install
    - npm test

# Deploy to Vercel
deploy-vercel:
  stage: deploy
  image: node:16
  script:
    # - cd Frontend
    - npm install -g vercel
    - vercel --token $VERCEL_TOKEN --prod
  only:
    - main  # Deploy only on the main branch
